
IGNORE_AUTHOR_GROUPS = [
  r'.*amayagaming\.com',
  r'.*ashgaming\.com',
  r'.*ballytech\.com',
  r'.*betdigital\.net',
  r'.*bigtimegaming\.com',
  r'.*blueprintgaming\.com',
  r'.*coregaming\.co\.uk',
  r'.*cryptologic\.com',
  r'.*derivco\.com',
  r'.*dunes-software\.com',
  r'.*electracade\.com',
  r'.*endemolgames\.com',
  r'.*endemolgaming\.com',
  r'.*endemoluk\.com',
  r'.*fincore\.com',
  r'.*fremantlemedia\.com',
  r'.*gmail\.com',
  r'.*grandparade\.co\.uk',
  r'.*igt\.com',
  r'.*IGT\.com',
  r'.*ingenuitygaming\.com',
  r'.*innopark\.in',
  r'.*instantwingaming\.com',
  r'.*mazooma\.co\.uk',
  r'.*metagu\.com',
  r'.*microgaming\.co\.uk',
  r'.*mobilewavesolutions\.com',
  r'.*mubaloo\.com',
  r'.*mx-digital\.com',
  r'.*nds\.com',
  r'.*netent\.com',
  r'.*nextgengaming\.com',
  r'.*pushgaming\.com',
  r'.*realisticgames\.co\.uk',
  r'.*red7mobile.com',
  r'.*sqs\.com',
  r'.*sqs-india\.com',
  r'.*squiz\.co\.uk',
  r'.*thetestpeople\.com',
  r'.*traffgen\.com',
  r'.*trifork\.com',
  r'unknown',
  r'.*wagerlogic\.com',
  r'.*wagermill\.com',
  r'.*whl\.co\.uk',
  r'.*williamhill\.co\.uk',
  r'.*williamhill\.com',
  r'.*WilliamHill\.com',
  r'.*williamsinteractive.com',
]

WIL_USERS_FULL = [
    'amarinpe', 'averkios.sigalas@openbet.com', 'rlamarca', 'sliapis', 'mariusz.jozala@openbet.com',
    'mhopgood', 'nspargo', 'eproias', 'solevent', 'malparon',
    'mgolab', 'jgournet', 'victoria.clarkson@openbet.com', 'gjoseph', 'ssubrama',
    'ggionis', 'dan.cooper@openbet.com', 'yjia', 'mwozniak', 'ldrougka',
    'atumanov', 'mkothari', 'clianos', 'tangelop', 'dtuplin', 'fserragn', 'khalid.shah@openbet.com',
    'bpreston', 'tpanourg', 'leon.mason@openbet.com', 'mbruel', 'rwilson', 'apiha', 'fasih.rana@openbet.com',
    'manel.naspreda@openbet.com', 'hli', 'awang', 'asharma', 'mjack', 'sfokeas', 'ekaloger',
    'raul.spilca@openbet.com', 'rconstab', 'jmendels', 'aaggelop', 'psansom', 'ekarakou', 'sratchfo',
    'stuart.quin@openbet.com', 'banil', 'dmisdani', 'swang', 'vliaras', 'marees', 'ywang', 'fparaske',
    'njones', 'rwalton', 'sspence', 'ajanzade', 'akatsika', 'yraja', 'araines', 'kpolychr', 'mshahida',
    'ddranidi', 'christopher.gomm@openbet.com', 'jpinero', 'lwalker', 'jbucklan', 'dguest',
    'jeevan.palakurty@openbet.com', 'oliver.whiteman@openbet.com', 'adrian.sosialuk@openbet.com',
    'amgad.souleiman@openbet.com', 'acartwright', 'bpowell', 'abenawra', 'jgorecki', 'thasler',
    'anoush.taheri@openbet.com', 'lmilioni', 'pbalas', 'tfoglia', 'ekhoo', 'aalam', 'lduran', 'pbouvier',
    'ggrigori', 'mparry', 'owain.john@openbet.com', 'iblacoe', 'ahaddad', 'jane.xia@openbet.com', 'ateja',
    'ddiamant', 'pietro.cuomo@openbet.com', 'lvamvour', 'ewallace', 'adimtsas', 'kkollias', 'achalats', 'jcrespo',
    'msharma', 'mbarnard', 'cpether', 'ademertz', 'srevesz', 'raloor', 'nbates', 'gpeterso', 'dalexand',
    'migration', 'medoatie', 'igiannop', 'alaskari', 'skakouri', 'rcastill', 'svenkata', 'pkaura', 'jostanga',
    'akrawczy', 'dboutaki', 'xdimaras', 'ikaragia', 'ibrucere', 'ebeta', 'saral.kaushik@openbet.com', 'apapai',
    'psalonit', 'adickins', 'andrzej.folga@openbet.com', 'amavroul', 'atsonou', 'andrew.summers@openbet.com',
    'mark.waghorn@openbet.com', 'ataylor', 'jsun', 'christopher.mccoy@openbet.com', 'ajackson', 'bbailey', 'fmuletma',
    'fangoura', 'smolinar', 'aballas', 'snechita', 'wangjia.sun@openbet.com', 'hchadwic', 'jclemins', 'aalexopo',
    'avezeanu', 'vsaxena', 'pdampani', 'aspandon', 'ngreator', 'matthew.byrd@openbet.com', 'mjieamta', 'plavra',
    'blewis', 'mdimopou', 'james.rennison@openbet.com', 'jskoumbo', 'rarnold', 'amegas', 'afurajco',
    'alexander.stone@openbet.com', 'czapanti', 'melliott', 'smeacher', 'james.billingham@openbet.com', 'fkhan',
    'robert.ssmith@openbet.com', 'jayub', 'rdelplan', 'zchan', 'ejowett', 'gmakrida', 'smazarak', 'aandoh',
    'chockley', 'hbouslim', 'tbuckle', 'cpitcher', 'lwenker', 'adam.kidd@openbet.com', 'ssilver', 'mahn', 'gevans',
    'vrevelas', 'tkouzina', 'fjahansh', 'ndelvero', 'eparadei', 'lturcan', 'william.knox-walker@openbet.com',
    'peter.dwyer@openbet.com', 'galford', 'npolydor', 'jhamdi', 'matt.shaile@openbet.com', 'dstanemi', 'wtawfik',
    'zkalampo', 'jshek', 'isanchez', 'mparker', 'amishra', 'bgomes', 'gvelimac', 'iain.rauch@openbet.com', 'jpreston',
    'vshatilo', 'dtsapani', 'gsingh', 'jadamu', 'ktsiopts', 'asvigkos', 'rzanelli', 'guruprasad.basavaraju@openbet.com',
    'gsilvers', 'cpallard', 'mnotaran', 'gbrouska', 'india-qc@openbet.com', 'mpatriko', 'spegg', 'icooke', 'kanderso',
    'david.williams@openbet.com', 'eercan', 'smehmood', 'shazleto', 'elappas', 'pkiruvan', 'akontaro',
    'shilpa.shivakumar@openbet.com', 'shamo.calliste@openbet.com', 'atorres', 'dbalotis', 'cmcguine', 'jdavies',
    'skontova', 'amassiah', 'zvasilei', 'jsutherl', 'nkorikis', 'hpark', 'enoguchi', 'chiara.cardamone@openbet.com',
    'sninos', 'ktsaprai', 'ggkelis', 'imiell', 'vbaciu', 'tslaim', 'rcubitt', 'spandran', 'glilis',
    'jaco.swanepoel@openbet.com', 'pvlachop', 'pgkolias', 'svarkey', 'jmiddlet', 'author', 'nicola.bird@openbet.com',
    'matias.rantanen@openbet.com', 'amichel', 'juneyt.donmez@openbet.com', 'gpoulis', 'ivoulgar', 'owhitema@openbet.com',
    'gtselos', 'fanjean.tsen@openbet.com ', 'mark.griffin@openbet.com', 'vgrigoro', 'rrajendr', 'jmaybowl', 'grmiller',
    'rlongoba', 'ayates', 'pmanolak', 'lbarlade', 'clewis', 'atsaousi', 'ahanson', 'eyates', 'luca.tosques@openbet.com',
    'lcoccia', 'ndsouza', 'stzoumer', 'swootton', 'cdesilva', 'james.evans@sgdigital.com', 'dkottali', 'itheodos',
    'swara', 'kseth', 'cmontoya', 'zoltan.kiss@openbet.com', 'iudageda', 'dfigueir', 'mabraham', 'mbell', 'medwards',
    'slakshmi', 'ddressle', 'apmatsag', 'ugangadh', 'mandrews', 'mprodrom', 'ppicci', 'gmckinno', 'abkumar', 'agekht',
    'asivakum', 'daniel.arias@openbet.com', 'stestagu', 'sebastian.phelps@openbet.com', 'antonio.alonzi@openbet.com',
    'openbet-rm', 'sroberts', 'mmurguia', 'tpagtzis', 'tseppi', 'jdarcy', 'ssripany', 'michael.uzoho@openbet.com',
    'sathanas', 'agoddard', 'achirosc', 'ivirdi', 'schauhan', 'jscottw', 'hnair', 'adam.hobden@sg-gaming.com', 'arangana',
    'akarageo', 'john.bass@openbet.com', 'cvalmas', 'vasilis.kontis@openbet.com', 'lwelch', 'steven.davies@openbet.com',
    'jbaddele', 'sbrahman', 'jbramley', 'andrew.whitehead@openbet.com', 'kholton', 'pvagenas', 'matthew.peel@openbet.com',
    'amallal', 'stharaka', 'lwoodhou', 'rsaltao', 'cchitty', 'ddemby', 'snaghibi', 'mheath', 'azoumpou', 'msinicco',
    'junderwo', 'mlyons', 'jallen', 'cian.omahony@openbet.com', 'mmassiah', 'nmetz', 'salexopo', 'mgheorgh', 'agiannis',
    'cramacha', 'sgkazemp', 'ctsagkou', 'bwessels', 'bduncan', 'madavey', 'sfigueir', 'vanastas', 'kdheena', 'btuna',
    'mborowie', 'jmatesan', 'andrew.january@openbet.com', 'dlolis', 'ppatelka', 'scassidy', 'sjayaram',
    'bryan.upton@openbet.com', 'szisakis', 'wbeaton', 'zfajkovi', 'swati.panda@openbet.com', 'sdelacru', 'slawson',
    'tdaltonl', 'vtoth', 'rkanchi', 'support@openbet.com', 'achalkia', 'jamie.hamilton@openbet.com ', 'mromani',
    'draviolo', 'awadood', 'jpolimon', 'spournar', 'ldavis', 'mhaque', 'ngowda', 'david.allan@openbet.com', 'xchen',
    'award', 'rgiancol', 'alexander.baird@openbet.com', 'dkolios', 'kyriakos.vallianatos@openbet.com', 'hdave', 'ptrianta',
    'matthew.turnbull@openbet.com', 'alessio.parente@openbet.com', 'jpabloro', 'xliu', 'knybakk', 'aantonia', 'plitsi',
    'ctrombet', 'plaughre', 'jhammer', 'glupascu', 'achatzis', 'pjames', 'joksenhe', 'eburchil', 'jsowden', 'dye',
    'antonis.theocharides@openbet.com', 'bshaw', 'ppanesar', 'dlee', 'alexandros.cheimarios@openbet.com', 'miurco',
    'snavales', 'rayner.lucas@openbet.com', 'lyndon.bennett@sg-gaming.com', 'jgan', 'kkalna', 'jabruce', 'gsmart',
    'celliott', 'dgonatas', 'majeoffr', 'msandler', 'pmichael', 'jpaisley', 'mnageswa', 'gkarampe',
    'adrian.smaranda@openbet.com', 'anita.nwabudike@openbet.com', 'cribot', 'mciazyns',
    'dominic.valentyne@openbet.com', 'brinalde', 'kntemagk', 'edward.saunders@openbet.com',
    'xmeng', 'miguel.gonzalez@openbet.com', 'tarun.mittal@openbet.com', 'abiafell', 'kkarouzo', 'nkatapid',
    'akarampa', 'mvlatas', 'sgourgar', 'dcummins', 'astraist', 'alacey', 'atiwari', 'rsutherl', 'kelby',
    'antony.ganesan@openbet.com', 'rsharma', 'ahobsons', 'mbiswas', 'gchatzik', 'cliontos', 'ebarrett', 'adowning',
    'dcarr', 'cpapadop', 'sfirth', 'vbosioli', 'hlouw', 'gkapidis', 'msamoila', 'kdimou', 'mion', 'adhami', 'sjoshi',
    'dandion', 'sbakkeby', 'ssyrgian', 'bop.mistry@openbet.com', 'mmanosha', 'rdalvi', 'jonatan.wallgren@openbet.com',
    'ddold', 'gkazadei', 'ndessipr', 'vkrishna', 'hcruz', 'nishan.karunatillake@openbet.com', 'mvalouis', 'jbrankin',
    'ifinlay', 'njarycze', 'ajessop', 'troberto', 'jdulaj', 'cthomas', 'kpapadim', 'krashad', 'acabbia', 'mmolino',
    'mike.lally@openbet.com', 'akataras', 'ljones', 'alwilson', 'ptelonis', 'mcrean', 'mkent', 'astarr', 'gchoumo',
    'bnikolop', 'glohiya', 'alee', 'kelvin.bland@openbet.com', 'ngiallel', 'ppinto', 'ssentanc', 'jneofoti', 'aachim',
    'sbristow', 'afarahza', 'mike.pledge@openbet.com', 'vghergus', 'alongwil', 'mvinayag', 'svijayku',
    'mark.rehorst-smith@openbet.com', 'jgarcias', 'rzilenas', 'mmavriop', 'sismith', 'imarouli', 'jpurring', 'gcalvert',
    'jhayes', 'pwillcox', 'mrenou', 'shough', 'mark.docherty@sg-gaming.com', 'mmarouda'
]

# WH People have been removed
# The following list should hold all the valid users. Any data coming from inactive
# users should be discarded. If it's empty, include them all.
VALID_USERS = [
  'aaggelop', 'aalam', 'aalexopo', 'aandoh', 'aballas', 'abiafell', 'achalats', 'achalkia',
  'achatzis', 'achirosc', 'adhami', 'adowning', 'afarahza', 'agoddard', 'ajackson', 'ajessop',
  'akarampa', 'akrawczy', 'alacey', 'alaskari', 'alee', 'alwilson', 'amallal', 'amassiah',
  'amavroul', 'amegas', 'amishra', 'apiha', 'arangana', 'asivakum', 'aspandon', 'ataylor',
  'ateja', 'atiwari', 'awadood', 'award', 'ayates', 'azoumpou', 'bbailey', 'bpreston',
  'brinalde', 'bshaw', 'bwessels', 'celliott', 'clewis', 'clianos', 'cmontoya', 'cpether',
  'cpitcher', 'ctsagkou', 'cvalmas', 'czapanti', 'dbalotis', 'dboutaki', 'dcummins', 'ddemby',
  'ddiamant', 'ddressle', 'dfigueir', 'dgonatas', 'dguest', 'dkolios', 'dkottali', 'draviolo',
  'dtsapani', 'dtuplin', 'ebarrett', 'ekarakou', 'elappas', 'eparadei', 'eproias', 'eyates',
  'fangoura', 'fjahansh', 'fkhan', 'gbrouska', 'gchoumo', 'gjoseph', 'gkapidis', 'gkarampe',
  'gkazadei', 'glilis', 'glohiya', 'glupascu', 'gmakrida', 'gmckinno', 'hdave', 'hli', 'hnair',
  'ibrucere', 'ifinlay', 'igiannop', 'ikaragia', 'imarouli', 'isanchez', 'itheodos', 'ivirdi',
  'ivoulgar', 'jabruce', 'jadamu', 'jayub', 'jbaddele', 'jbucklan', 'jclemins', 'jdarcy',
  'jdavies', 'jdulaj', 'jgorecki', 'jmatesan', 'jmaybowl', 'joksenhe', 'jostanga', 'jpabloro',
  'jpinero', 'jscottw', 'jskoumbo', 'jsowden', 'jsun', 'junderwo', 'kanderso', 'kdimou',
  'kevangel', 'kholton', 'kkollias', 'kntemagk', 'kseth', 'ktsiopts', 'lbarlade', 'ldavis',
  'ldrougka', 'lduran', 'ljones', 'lmilioni', 'lvamvour', 'lwelch', 'lwenker', 'mahn',
  'mandrews', 'mbell', 'mbiswas', 'mcrean', 'mdimopou', 'medoatie', 'mheath', 'mion', 'mjack',
  'mkent', 'mmanosha', 'mmarouda', 'mmassiah', 'mmolino', 'mmurguia', 'mparry', 'mpatriko',
  'mprodrom', 'mrenou', 'msandler', 'mshahida', 'msharma', 'msinicco', 'mvalouis', 'mvinayag',
  'mvlatas', 'mwozniak', 'nbates', 'ndelvero', 'ndsouza', 'ngiallel', 'ngowda', 'njarycze',
  'njones', 'nkatapid', 'npolydor', 'pbalas', 'pbouvier', 'pdampani', 'pkaura', 'pkiruvan',
  'plaughre', 'plavra', 'plitsi', 'pmanolak', 'pmichael', 'ppinto', 'psalonit', 'psansom',
  'ptelonis', 'ptrianta', 'pvagenas', 'pvlachop', 'raloor', 'rarnold', 'rconstab', 'rcubitt',
  'rdalvi', 'rgiancol', 'rkanchi', 'rlamarca', 'rrajendr', 'rsaltao', 'rsharma', 'rzanelli',
  'sbakkeby', 'sbrahman', 'sbristow', 'scassidy', 'schauhan', 'sfigueir', 'shough', 'sismith',
  'sjayaram', 'sjoshi', 'skakouri', 'skontova', 'slakshmi', 'slawson', 'smeacher', 'smolinar',
  'snaghibi', 'sninos', 'solevent', 'spandran', 'spournar', 'srevesz', 'sroberts', 'ssentanc',
  'ssilver', 'sspence', 'ssripany', 'ssyrgian', 'stestagu', 'stzoumer', 'svarkey', 'svenkata',
  'swootton', 'tangelop', 'tbuckle', 'tdaltonl', 'thasler', 'tpanourg', 'troberto', 'tseppi',
  'tslaim', 'ugangadh', 'vanastas', 'vbaciu', 'vbosioli', 'vghergus', 'vliaras', 'vrevelas',
  'vsaxena', 'vtoth', 'wbeaton', 'xdimaras', 'yjia', 'yraja', 'ywang', 'zfajkovi', 'zvasilei',
  ]

WIL_USERS_ACTIVE = {
  'atiwari': 'Abhijit Tiwari',
  'alee': 'Adrian Lee',
  'aaggelop': 'Aggelos Aggelopoulos',
  'arangana': 'Aksatha Ranganath',
  'ataylor': 'Alan Taylor',
  'achirosc': 'Alina Chirosca',
  'aandoh': 'Andrew Andoh',
  'award': 'Andrew Ward',
  'apiha': 'Antonio Piha',
  'aspandon': 'Antonis Spandonidis',
  'asivakum': 'Anusha Sivakumar',
  'bshaw': 'Bernard Shaw',
  'bpreston': 'Bruce Preston',
  'cpether': 'Chris Pether',
  'cvalmas': 'Chrisopher Valmas',
  'dcummins': 'Daniel Cummins',
  'dkapouka': 'Dimitrios Kapoukakis',
  'dkolios': 'Dimitris Kolios',
  'dveneros': 'Dimitris Veneros',
  'dgonatas': 'Dionysis Gonatas',
  'eparadei': 'Elli Paradeisanou',
  'flaxalde': 'Facundo Laxalde',
  'fsusljek': 'Franjo Susljek',
  'glupascu': 'Gabriel Lipascu',
  'gchoumo': 'George Choumos',
  'gkarampe': 'George Karampelas',
  'gmakrida': 'George Makridakis',
  'gkazadei': 'Giannis Kazadeis',
  'imarouli': 'Iakovos Maroulis',
  'ibrucere': 'Ian Bruce-Reid',
  'jayub': 'Jibran Ayub',
  'jdarcy': 'John Darcy',
  'kevangel': 'Kostas Evangelou',
  'kntemagk': 'Kostas Ntemagkos',
  'lwenker': 'Lars Wenker',
  'ljones': 'Liam Jones',
  'mmanosha': 'Mahendran Manoshan',
  'medoatie': 'Marcos Edo Atienza',
  'mion': 'Marius Ion',
  'mvinayag': 'Megala Vinayagam',
  'mvalouis': 'Michail Valouiskof',
  'msinicco': 'Michele Sinicco',
  'nkatapid': 'Nikos Katapidis',
  'nvittas': 'Nikos Vittas',
  'psalonit': 'Panagiotis Salonitis',
  'pvagenas': 'Panagiotis Vagenas',
  'pvlachop': 'Paraskevi Vlachopoulou',
  'pmiranda': 'Pedro Miranda',
  'ppinto': 'Pedro Pinto',
  'rkanchi': 'Rahul Kanchi',
  'rlamarca': 'Rosa La Marca',
  'rconstab': 'Russell Constable',
  'scassidy': 'Sam Cassidy',
  'smolinar': 'Santino Molinaro',
  'snaghibi': 'Sareh Naghibirad',
  'sismith': 'Simon Smith',
  'ssripany': 'Songkran Sripanya',
  'sbrahman': 'Sonia Brahmane',
  'solevent': 'Sotiris Leventis',
  'sjayaram': 'Srinivasan Jayaraman',
  'shough': 'Stephen Hough',
  'spandran': 'Suresh Pandranki',
  'tpanourg': 'Tassos Panourgias',
  'tdaltonl': 'Thomas Dalton-Locke',
  'vghergus': 'Valentin Ghergus',
  'vvafeiad': 'Vangelis Vafeiadis',
  'vrevelas': 'Vasileios Revelas',
  'vtoth': 'Veronika Toth',
  'vbaciu': 'Vlad Baciu',
  'yraja': 'Yogesh Raja'
}